/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'description' : string,
  'category' : ActivityCategory,
}
export type ActivityCategory = { 'social' : null } |
  { 'research' : null } |
  { 'administrative' : null } |
  { 'academic' : null };
export interface StudentPerformance {
  'id' : bigint,
  'studentId' : string,
  'semester' : string,
  'studentName' : string,
  'subject' : string,
  'grade' : string,
  'remarks' : [] | [string],
}
export interface Target {
  'id' : bigint,
  'status' : TargetStatus,
  'title' : string,
  'description' : string,
  'deadline' : string,
}
export type TargetStatus = { 'achieved' : null } |
  { 'pending' : null } |
  { 'inProgress' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createActivity' : ActorMethod<
    [string, string, string, ActivityCategory],
    undefined
  >,
  'createStudentPerformance' : ActorMethod<
    [string, string, string, string, string, [] | [string]],
    undefined
  >,
  'createTarget' : ActorMethod<
    [string, string, string, TargetStatus],
    undefined
  >,
  'deleteActivity' : ActorMethod<[bigint], undefined>,
  'deleteStudentPerformance' : ActorMethod<[bigint], undefined>,
  'deleteTarget' : ActorMethod<[bigint], undefined>,
  'getActivity' : ActorMethod<[bigint], Activity>,
  'getAllActivities' : ActorMethod<[], Array<Activity>>,
  'getAllStudentPerformances' : ActorMethod<[], Array<StudentPerformance>>,
  'getAllTargets' : ActorMethod<[], Array<Target>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStudentPerformance' : ActorMethod<[bigint], StudentPerformance>,
  'getTarget' : ActorMethod<[bigint], Target>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateActivity' : ActorMethod<
    [bigint, string, string, string, ActivityCategory],
    undefined
  >,
  'updateStudentPerformance' : ActorMethod<
    [bigint, string, string, string, string, string, [] | [string]],
    undefined
  >,
  'updateTarget' : ActorMethod<
    [bigint, string, string, string, TargetStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];