/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActivityCategory = IDL.Variant({
  'social' : IDL.Null,
  'research' : IDL.Null,
  'administrative' : IDL.Null,
  'academic' : IDL.Null,
});
export const TargetStatus = IDL.Variant({
  'achieved' : IDL.Null,
  'pending' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : ActivityCategory,
});
export const StudentPerformance = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Text,
  'semester' : IDL.Text,
  'studentName' : IDL.Text,
  'subject' : IDL.Text,
  'grade' : IDL.Text,
  'remarks' : IDL.Opt(IDL.Text),
});
export const Target = IDL.Record({
  'id' : IDL.Nat,
  'status' : TargetStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createActivity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ActivityCategory],
      [],
      [],
    ),
  'createStudentPerformance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'createTarget' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, TargetStatus],
      [],
      [],
    ),
  'deleteActivity' : IDL.Func([IDL.Nat], [], []),
  'deleteStudentPerformance' : IDL.Func([IDL.Nat], [], []),
  'deleteTarget' : IDL.Func([IDL.Nat], [], []),
  'getActivity' : IDL.Func([IDL.Nat], [Activity], ['query']),
  'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getAllStudentPerformances' : IDL.Func(
      [],
      [IDL.Vec(StudentPerformance)],
      ['query'],
    ),
  'getAllTargets' : IDL.Func([], [IDL.Vec(Target)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudentPerformance' : IDL.Func(
      [IDL.Nat],
      [StudentPerformance],
      ['query'],
    ),
  'getTarget' : IDL.Func([IDL.Nat], [Target], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateActivity' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, ActivityCategory],
      [],
      [],
    ),
  'updateStudentPerformance' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateTarget' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, TargetStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActivityCategory = IDL.Variant({
    'social' : IDL.Null,
    'research' : IDL.Null,
    'administrative' : IDL.Null,
    'academic' : IDL.Null,
  });
  const TargetStatus = IDL.Variant({
    'achieved' : IDL.Null,
    'pending' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : ActivityCategory,
  });
  const StudentPerformance = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Text,
    'semester' : IDL.Text,
    'studentName' : IDL.Text,
    'subject' : IDL.Text,
    'grade' : IDL.Text,
    'remarks' : IDL.Opt(IDL.Text),
  });
  const Target = IDL.Record({
    'id' : IDL.Nat,
    'status' : TargetStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createActivity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ActivityCategory],
        [],
        [],
      ),
    'createStudentPerformance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'createTarget' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, TargetStatus],
        [],
        [],
      ),
    'deleteActivity' : IDL.Func([IDL.Nat], [], []),
    'deleteStudentPerformance' : IDL.Func([IDL.Nat], [], []),
    'deleteTarget' : IDL.Func([IDL.Nat], [], []),
    'getActivity' : IDL.Func([IDL.Nat], [Activity], ['query']),
    'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getAllStudentPerformances' : IDL.Func(
        [],
        [IDL.Vec(StudentPerformance)],
        ['query'],
      ),
    'getAllTargets' : IDL.Func([], [IDL.Vec(Target)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudentPerformance' : IDL.Func(
        [IDL.Nat],
        [StudentPerformance],
        ['query'],
      ),
    'getTarget' : IDL.Func([IDL.Nat], [Target], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateActivity' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, ActivityCategory],
        [],
        [],
      ),
    'updateStudentPerformance' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateTarget' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, TargetStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };