/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Target {
    id: bigint;
    status: TargetStatus;
    title: string;
    description: string;
    deadline: string;
}
export interface StudentPerformance {
    id: bigint;
    studentId: string;
    semester: string;
    studentName: string;
    subject: string;
    grade: string;
    remarks?: string;
}
export interface Activity {
    id: bigint;
    title: string;
    date: string;
    description: string;
    category: ActivityCategory;
}
export interface UserProfile {
    name: string;
}
export enum ActivityCategory {
    social = "social",
    research = "research",
    administrative = "administrative",
    academic = "academic"
}
export enum TargetStatus {
    achieved = "achieved",
    pending = "pending",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createActivity(title: string, description: string, date: string, category: ActivityCategory): Promise<void>;
    createStudentPerformance(studentName: string, studentId: string, subject: string, grade: string, semester: string, remarks: string | null): Promise<void>;
    createTarget(title: string, description: string, deadline: string, status: TargetStatus): Promise<void>;
    deleteActivity(id: bigint): Promise<void>;
    deleteStudentPerformance(id: bigint): Promise<void>;
    deleteTarget(id: bigint): Promise<void>;
    getActivity(id: bigint): Promise<Activity>;
    getAllActivities(): Promise<Array<Activity>>;
    getAllStudentPerformances(): Promise<Array<StudentPerformance>>;
    getAllTargets(): Promise<Array<Target>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getStudentPerformance(id: bigint): Promise<StudentPerformance>;
    getTarget(id: bigint): Promise<Target>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateActivity(id: bigint, title: string, description: string, date: string, category: ActivityCategory): Promise<void>;
    updateStudentPerformance(id: bigint, studentName: string, studentId: string, subject: string, grade: string, semester: string, remarks: string | null): Promise<void>;
    updateTarget(id: bigint, title: string, description: string, deadline: string, status: TargetStatus): Promise<void>;
}
import type { Activity as _Activity, ActivityCategory as _ActivityCategory, StudentPerformance as _StudentPerformance, Target as _Target, TargetStatus as _TargetStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createActivity(arg0: string, arg1: string, arg2: string, arg3: ActivityCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createActivity(arg0, arg1, arg2, to_candid_ActivityCategory_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createActivity(arg0, arg1, arg2, to_candid_ActivityCategory_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createStudentPerformance(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudentPerformance(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudentPerformance(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createTarget(arg0: string, arg1: string, arg2: string, arg3: TargetStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTarget(arg0, arg1, arg2, to_candid_TargetStatus_n6(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTarget(arg0, arg1, arg2, to_candid_TargetStatus_n6(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteActivity(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivity(arg0);
            return result;
        }
    }
    async deleteStudentPerformance(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudentPerformance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudentPerformance(arg0);
            return result;
        }
    }
    async deleteTarget(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTarget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTarget(arg0);
            return result;
        }
    }
    async getActivity(arg0: bigint): Promise<Activity> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivity(arg0);
                return from_candid_Activity_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivity(arg0);
            return from_candid_Activity_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivities();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivities();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudentPerformances(): Promise<Array<StudentPerformance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudentPerformances();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudentPerformances();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTargets(): Promise<Array<Target>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTargets();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTargets();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentPerformance(arg0: bigint): Promise<StudentPerformance> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentPerformance(arg0);
                return from_candid_StudentPerformance_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentPerformance(arg0);
            return from_candid_StudentPerformance_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTarget(arg0: bigint): Promise<Target> {
        if (this.processError) {
            try {
                const result = await this.actor.getTarget(arg0);
                return from_candid_Target_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTarget(arg0);
            return from_candid_Target_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateActivity(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: ActivityCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivity(arg0, arg1, arg2, arg3, to_candid_ActivityCategory_n3(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivity(arg0, arg1, arg2, arg3, to_candid_ActivityCategory_n3(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateStudentPerformance(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentPerformance(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentPerformance(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateTarget(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: TargetStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTarget(arg0, arg1, arg2, arg3, to_candid_TargetStatus_n6(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTarget(arg0, arg1, arg2, arg3, to_candid_TargetStatus_n6(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_ActivityCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityCategory): ActivityCategory {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Activity_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_StudentPerformance_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentPerformance): StudentPerformance {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TargetStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TargetStatus): TargetStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Target_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Target): Target {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    studentId: string;
    semester: string;
    studentName: string;
    subject: string;
    grade: string;
    remarks: [] | [string];
}): {
    id: bigint;
    studentId: string;
    semester: string;
    studentName: string;
    subject: string;
    grade: string;
    remarks?: string;
} {
    return {
        id: value.id,
        studentId: value.studentId,
        semester: value.semester,
        studentName: value.studentName,
        subject: value.subject,
        grade: value.grade,
        remarks: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.remarks))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TargetStatus;
    title: string;
    description: string;
    deadline: string;
}): {
    id: bigint;
    status: TargetStatus;
    title: string;
    description: string;
    deadline: string;
} {
    return {
        id: value.id,
        status: from_candid_TargetStatus_n20(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        deadline: value.deadline
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    date: string;
    description: string;
    category: _ActivityCategory;
}): {
    id: bigint;
    title: string;
    date: string;
    description: string;
    category: ActivityCategory;
} {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        description: value.description,
        category: from_candid_ActivityCategory_n10(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    social: null;
} | {
    research: null;
} | {
    administrative: null;
} | {
    academic: null;
}): ActivityCategory {
    return "social" in value ? ActivityCategory.social : "research" in value ? ActivityCategory.research : "administrative" in value ? ActivityCategory.administrative : "academic" in value ? ActivityCategory.academic : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    achieved: null;
} | {
    pending: null;
} | {
    inProgress: null;
}): TargetStatus {
    return "achieved" in value ? TargetStatus.achieved : "pending" in value ? TargetStatus.pending : "inProgress" in value ? TargetStatus.inProgress : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentPerformance>): Array<StudentPerformance> {
    return value.map((x)=>from_candid_StudentPerformance_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Target>): Array<Target> {
    return value.map((x)=>from_candid_Target_n18(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityCategory): _ActivityCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TargetStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TargetStatus): _TargetStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityCategory): {
    social: null;
} | {
    research: null;
} | {
    administrative: null;
} | {
    academic: null;
} {
    return value == ActivityCategory.social ? {
        social: null
    } : value == ActivityCategory.research ? {
        research: null
    } : value == ActivityCategory.administrative ? {
        administrative: null
    } : value == ActivityCategory.academic ? {
        academic: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TargetStatus): {
    achieved: null;
} | {
    pending: null;
} | {
    inProgress: null;
} {
    return value == TargetStatus.achieved ? {
        achieved: null
    } : value == TargetStatus.pending ? {
        pending: null
    } : value == TargetStatus.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
